# This is the config file for building and testing Geo::OGC::Service::WFS with Travis-ci.org

language: perl
perl:
  - "5.10"

before_install:
  - sudo apt-get install libexpat-dev libpq-dev
  - wget https://github.com/ajolma/Geo-GDAL-2.01/archive/2.010201.tar.gz
  - tar xf Geo-GDAL-2.01-2.010201.tar.gz
  - cd Geo-GDAL-2.01-2.010201
  - perl Makefile.PL
  - make
  - make test
  - sudo make install
  - cd ..

install:
  - cpanm -v --installdeps --notest .

script: "perl Makefile.PL; make test"

branches:
  only:
    - master

notifications:
  recipients:
    - ari.jolma@gmail.com
  email:
    on_success: change
    on_failure: always
